---
title: "Week 12"
author: "Job van de Visse"
date: "2026-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(compmus)
library(ggdendro)
library(heatmaply)
library(ggplot2)
```

```{r}
get_conf_mat <- function(fit) {
  outcome <- .get_tune_outcome_names(fit)
  fit |> 
    collect_predictions() |> 
    conf_mat(truth = outcome, estimate = .pred_class)
}  

get_pr <- function(fit) {
  fit |> 
    conf_mat_resampled() |> 
    group_by(Prediction) |> mutate(precision = Freq / sum(Freq)) |> 
    group_by(Truth) |> mutate(recall = Freq / sum(Freq)) |> 
    ungroup() |> filter(Prediction == Truth) |> 
    select(class = Prediction, precision, recall)
}  
```


```{r}
Emily <- read_csv("./dat/Emily.csv")

Emily_juice <-
  recipe(
    `Track Name` ~
      Danceability +
      Energy +
      Loudness +
      Speechiness +
      Acousticness +
      Instrumentalness +
      Liveness +
      Valence +
      Tempo +
      `Duration (ms)`,
    data = Emily
  ) |>
  step_center(all_predictors()) |>
  step_scale(all_predictors()) |> 
  # step_range(all_predictors()) |> 
  prep(Emily |> mutate(`Track Name` = str_trunc(`Track Name`, 36))) |>
  juice() |>
  column_to_rownames("Track Name")


```

```{r}
Emily_dist <- dist(Emily_juice, method = "euclidean")
Emily_dist |> 
  hclust(method = "single") |> # Try single, average, and complete.
  dendro_data() |>
  ggdendrogram()
```

```{r}
heatmaply(
  Emily_juice,
  hclustfun = hclust,
  hclust_method = "average",  # Change for single, average, or complete linkage.
  dist_method = "euclidean"
)
```

```{r}
Chester2<- read_csv("./dat/Chester.csv")
Emily2 <- read_csv("./dat/Emily.csv")
```

```{r}
LP <-
  bind_rows(
    Chester2|> mutate(Playlist = "Chester"),
    Emily2|> mutate(Playlist = "Emily" )
  )
```

```{r}
LP_recipe <-
  recipe(
    Playlist ~
      Danceability +
      Energy +
      Loudness +
      Speechiness +
      Acousticness +
      Instrumentalness +
      Liveness +
      Valence +
      Tempo +
      `Duration (ms)`,
    data = LP                    # Use the same name as the previous block.
  ) |>
  step_center(all_predictors()) |>
  step_scale(all_predictors())      # Converts to z-scores.
  # step_range(all_predictors())    # Sets range to [0, 1].
```


```{r}
LP_cv <- LP |> vfold_cv(5)
knn_model <-
  nearest_neighbor(neighbors = 1) |>
  set_mode("classification") |> 
  set_engine("kknn")
LP_knn <- 
  workflow() |> 
  add_recipe(LP_recipe) |> 
  add_model(knn_model) |> 
  fit_resamples(LP_cv, control = control_resamples(save_pred = TRUE))
LP_knn |> get_pr()
```
```{r}
LP_knn |> get_conf_mat() |> autoplot(type = "mosaic")
```

```{r}
forest_model <-
  rand_forest() |>
  set_mode("classification") |> 
  set_engine("ranger", importance = "impurity")
LP_forest <- 
  workflow() |> 
  add_recipe(LP_recipe) |> 
  add_model(forest_model) |> 
  fit_resamples(
    LP_cv, 
    control = control_resamples(save_pred = TRUE)
  )
```

```{r}
LP_forest |> get_pr()
```

```{r}
workflow() |> 
  add_recipe(LP_recipe) |> 
  add_model(forest_model) |> 
  fit(LP) |> 
  pluck("fit", "fit", "fit") |>
  ranger::importance() |> 
  enframe() |> 
  mutate(name = fct_reorder(name, value)) |> 
  ggplot(aes(name, value)) + 
  geom_col() + 
  coord_flip() +
  theme_minimal() +
  labs(x = NULL, y = "Importance")
```

```{r}
LP |>
  ggplot(aes(x = Energy, y = Loudness, colour = Playlist, size = Tempo)) +
  geom_point(alpha = 0.8) +
  scale_color_viridis_d() +
  labs(
    x = "Energy",
    y = "Loudness",
    size = "Tempo",
    colour = "Playlist"
  )
```

